{{- if hasKey .Values "serviceAccount" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "base-chart.name" . }}-sa
  namespace: {{ .Values.app.namespace }}
  labels:
    router: {{ .type }}
    {{- include "base-chart.selectorLabels" . | nindent 4 }}
    {{- if .Values.customLabels }}
    {{- range .Values.customLabels }}
    {{ .name }}: {{ .value }}
    {{- end }}
    {{- end }}
  annotations:
    {{- include "base-chart.annotations" . | nindent 4 }}
    {{- if .Values.customAnnotations }}
    {{- range .Values.customAnnotations }}
    {{ .name }}: {{ .value }}
    {{- end }}
    {{- end }}  
    {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
